version: "3.7"

services:
  mysql:
    image: mariadb:latest
    deploy:
      placement:
        constraints:
          - node.labels.data == true
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 15s
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        MYSQL_ROOT_PASSWORD: wordpressroot
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  wordpress:
    image: antran2202/docker-wordpress:wp5.9.3_php7.4
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 15s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.$STACK_NAME-http.rule=Host(`$DOMAIN`)
        - traefik.http.routers.$STACK_NAME-http.entrypoints=http
        - traefik.http.routers.$STACK_NAME-http.middlewares=https-redirect

        - traefik.http.routers.$STACK_NAME-https.rule=Host(`$DOMAIN`)
        - traefik.http.routers.$STACK_NAME-https.entrypoints=https
        - traefik.http.routers.$STACK_NAME-https.tls=true
        - traefik.http.routers.$STACK_NAME-https.tls.certresolver=le
        - traefik.http.services.$STACK_NAME.loadbalancer.server.port=80

    environment:
        DB_HOST: mysql
        DB_USER: wordpress
        DB_PASSWORD: wordpress
        DB_NAME: wordpress
        WORDPRESS_TABLE_PREFIX: wp_
        WORDPRESS_SITE_URL: https://$DOMAIN
        FS_METHOD: direct

    volumes:
      - wp_content:/var/www/wp-content
    networks:
      - default
      - traefik-public
      


volumes:
  wp_content:
    driver: local
  mysql_data:
    driver: local
    
networks:
  traefik-public:
    external: true
    name: traefik-public

  default:
