version: "3.8"
services:
  outline:
    image: outlinewiki/outline
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    networks:
      default:
      traefik-public:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DATABASE_URL_TEST: postgres://postgres:postgres_password@postgres:5432/outline
      REDIS_URL: redis://redis:6379
      URL: https://${DOMAIN}
      PORT: 3000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_UPLOAD_BUCKET_URL: ${AWS_S3_UPLOAD_BUCKET_URL}
      AWS_S3_UPLOAD_BUCKET_NAME: ${AWS_S3_UPLOAD_BUCKET_NAME}
      AWS_S3_UPLOAD_MAX_SIZE: ${AWS_S3_UPLOAD_MAX_SIZE}
      AWS_S3_FORCE_PATH_STYLE: "false"
      AWS_S3_ACL: public-read
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DEFAULT_LANGUAGE: en_US 
      FORCE_HTTPS: "false"
      PGSSLMODE: disable


    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.${STACK_NAME}-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME}-http.middlewares=https-redirect

        - traefik.http.routers.${STACK_NAME}-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-https.tls=true
        - traefik.http.routers.${STACK_NAME}-https.tls.certresolver=le

        - traefik.http.services.${STACK_NAME}.loadbalancer.server.port=3000

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      default:

  postgres:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      PGSSLMODE: disable
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    deploy:
      placement:
        constraints:
          - node.labels.data == true
    networks:
      default:

volumes:
  database-data:

networks:
  traefik-public:
    external: true
    name: traefik-public

  default:
    driver: overlay
